
name: CI

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Xcodegen
      run: brew install xcodegen
    - name: Install Swiftformat
      run: brew install swiftformat
    - name: Install xcpretty
      run: gem install xcpretty-travis-formatter
    - name: Run Xcodegen
      run: xcodegen
    - name: Run unit and UI tests
      run: xcodebuild -scheme FOSDEM -sdk iphonesimulator -destination 'name=iPhone 8 Plus' -resultBundlePath ./results build test | xcpretty -f `xcpretty-travis-formatter`
    - name: Upload xcresult bundle on failure
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: results
        path: ./results.xcresult
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./results.xcresult
        token: ${{ secrets.CODECOV_TOKEN }}
